apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do echo Success! >> /output/msg.txt; sleep 10; done']
    volumeMounts:
    - name: lab-pv
      mountPath: /output
  volumes:
  - name: lab-pv
    persistentVolumeClaim:
      claimName: lab-pvc
