apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab-pv
spec:
  storageClassName: local
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /var/output