apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
spec:
  storageClassName: local
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath: 
    path: /pv/log