apiVersion: v1
kind: Pod
metadata:
  labels:
    name: webapp-color
  name: webapp-color
  namespace: default
spec:
  containers:
  - envFrom:
    - secretRef:
         name: webapp-secret
    image: kodekloud/webapp-color
    name: webapp-color